import csv

with open('./data/listings.csv', 'r') as f:
    reader = csv.DictReader(f)
    with open('./data/listings_clean.csv','w') as file:
        file.write('id,name,host_name,host_is_superhost,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,beds,price,review_scores_rating\n')
    with open('./data/listings_clean.csv','a',newline='') as file:
        col = ['id','name','host_name','host_is_superhost','host_neighbourhood','neighbourhood_cleansed','neighbourhood_group_cleansed','beds','price','review_scores_rating']
        writer = csv.DictWriter(file, fieldnames=col)
        for line in reader:
            del line['availability_365']
            del line['review_scores_checkin']
            del line['host_has_profile_pic']
            del line['minimum_maximum_nights']
            del line['maximum_maximum_nights']
            del line['review_scores_cleanliness']
            del line['calculated_host_listings_count_private_rooms']
            del line['host_thumbnail_url']
            del line['host_picture_url']
            del line['listing_url']
            del line['last_review']
            del line['scrape_id']
            del line['amenities']
            del line['bathrooms_text']
            del line['calculated_host_listings_count']
            del line['neighbourhood']
            del line['host_verifications']
            del line['calendar_updated']
            del line['first_review']
            del line['maximum_nights']
            del line['host_listings_count']
            del line['review_scores_communication']
            del line['picture_url']
            del line['host_url']
            del line['property_type']
            del line['number_of_reviews_l30d']
            del line['host_response_rate']
            del line['host_response_time']
            del line['last_scraped']
            del line['review_scores_value']
            del line['host_total_listings_count']
            del line['minimum_nights']
            del line['host_acceptance_rate']
            del line['description']
            del line['number_of_reviews']
            del line['availability_30']
            del line['minimum_nights_avg_ntm']
            del line['number_of_reviews_ltm']
            del line['host_since']
            del line['license']
            del line['calculated_host_listings_count_entire_homes']
            del line['host_location']
            del line['has_availability']
            del line['longitude']
            del line['maximum_nights_avg_ntm']
            del line['host_about']
            del line['availability_60']
            del line['calendar_last_scraped']
            del line['neighborhood_overview']
            del line['accommodates']
            del line['availability_90']
            del line['review_scores_accuracy']
            del line['bedrooms']
            del line['host_id']
            del line['calculated_host_listings_count_shared_rooms']
            del line['reviews_per_month']
            del line['maximum_minimum_nights']
            del line['minimum_minimum_nights']
            del line['bathrooms']
            del line['review_scores_location']
            del line['instant_bookable']
            del line['room_type']
            del line['host_identity_verified']
            del line['latitude']
            writer.writerow(line)